services:
  backend:
    build:
      context: ./server
    container_name: syncspark-backend
    ports:
      - "3001:3001"
    env_file:
      - ./server/.env
    restart: unless-stopped
    # Uncomment the following to mount code for live reload in dev
    # volumes:
    #   - ./server:/app
